version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: umap12345
      POSTGRES_DB: viethistory
    networks:
      - viethistory-network
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
networks:
  viethistory-network:
volumes:
  postgres: